### PR TITLE
Gave units direction and other fixes

### PR DESCRIPTION
**Pull request by AndreBacic**
@Smiley-Cartoons please merge when you see fit

### CODE REVIEW

**Comment by AndreBacic** [comment]
@Smiley-Cartoons I added you as reviewer without understanding what that role means. Sorry about that.

**Comment by AndreBacic** [comment]
Thank you!

**Comment by Smiley-Cartoons** [comment]
It's ok 👍

**Comment by Smiley-Cartoons** [comment]
So is there a way to view the game at this stage like the pitcrew website we could see it as we were coding? Or does that not exist for this? Also what should I be doing as the designer right now? Y'all can work with the burger right now right?

**Comment by AndreBacic** [comment]
As for deployment, there's not enough to deploy to a gh-pages branch yet :(

**Comment by AndreBacic** [comment]
In terms of design, we need more burger pics and a background/map instead of a green base map

**Comment by Smiley-Cartoons** [comment]
Ok I see

**Comment by Smiley-Cartoons** [comment]
Well I already put some burger walking forward and backward in their

**Comment by AndreBacic** [comment]
We can't do a lot with the burger because we need the following images, with up, down, right, and left versions:
- walking animation (we have up and down but no right or left)
- fighting animation (no images)
- dying animation (no images)

**Comment by Smiley-Cartoons** [comment]
Ok

**Comment by AndreBacic** [comment]
And of course up, down, right and left images for any other animations you want (like a shooting or spawning animation)

**Comment by Smiley-Cartoons** [comment]
I'll start working on those

**Comment by AndreBacic** [comment]
Thank you!

**Comment by AndreBacic** [comment]
You know, I should have written all that in Updates instead of this old pull request... I'll repost the points

**Comment by Smiley-Cartoons** [comment]
Ok great! When you say right and left animations you mean the burger walking to the left and right, correct?

**Comment by AndreBacic** [comment]
Yes

**Comment by AndreBacic** [comment]
And maybe not exactly fully turned to the left or right (that might look weird) but turned 5-10 degrees toward the user so that it... looks better. I'm not sure how to describe it well, but it's what Kingdom Rush did for their animations.

**Pull request merged**
