### PR TITLE
andre-bacic-changes

### PR DESCRIPTION
**Pull request by AndreBacic**
With these changes we use typescript to make the code much more understandable.

### CODE REVIEW

**Comment by AndreBacic** [comment]
@Smiley-Cartoons please merge (if you approve of using typescript)

**Comment by AndreBacic** [comment]
@Moybot2000 now you need to learn to use typescript (which is easy if you already know javascript)

**Comment by Moybot2000** [comment]
im doing my w3schools im currently on Javascript output

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by AndreBacic** [comment]
Excellent!

btw typescript is just javascript but you tell the computer what type of data is being used. Then, the editor can catch bugs far more easily for you. It also allows you to create your own types and to define classes that have more meaning to them because you know what sort of data they hold/use.

**Comment by AndreBacic** [comment]
Thank you!

**Pull request merged**
